
export const POKEMON_LIST_LOADING = 'POKEMON_LIST_LOADING';
export const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS';
export const POKEMON_LIST_FAILURE = 'POKEMON_LIST_FAILURE';

export const POKEMON_SINGLE_LOADING = 'POKEMON_SINGLE_LOADING';
export const POKEMON_SINGLE_SUCCESS = 'POKEMON_SINGLE_SUCCESS';
export const POKEMON_SINGLE_FAILURE = 'POKEMON_SINGLE_FAILURE';